language: node_js
node_js:
  - "node"
before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
script: yarn test
os: linux
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - mesa-utils
    - xvfb
    - libgl1-mesa-dri
    - libglapi-mesa
    - libosmesa6
before_deploy:
  - cd packages/cookbook && yarn run build
deploy:
  provider: surge
  project: build
  domain: gl-react-cookbook.surge.sh
  skip_cleanup: true
